apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "teslamate.fullname" . }}-teslamate"
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
type: Opaque
data:
  secretkey: {{ .Values.secretkey | b64enc }}
  database_user: {{ .Values.database_user | b64enc }}
  database_pass: {{ .Values.database_pass | b64enc }}
  database_name: {{ .Values.database_name | b64enc }}
